matrix:
  include:
  - os: linux
    sudo: required
    env:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
    - ARCH_TRAVIS_CONFIRM_YES=1
    - RELEASE="alinstaller-$(date +%Y.%m.%d)-$TRAVIS_TAG-x86_64.iso"
    script:
    - while true; do echo [PING]; sleep 100; done &
    - bash ./.arch-travis.sh

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - archiso
  - gtk3
  - python-babel
  - python-gobject
  - python-psutil
  - python-pylint
  - python-pythondialog
  - python-setuptools
  script:
  - sudo pacman-key --init
  - sudo pacman-key --populate archlinux
  # reduce image size:
  - sudo sed -i 's/\(mksquashfs .*\)-comp/\1-b 1024K -comp/' /bin/mkarchiso
  - pylint --additional-builtins=_ --disable=arguments-differ,broad-except,cyclic-import,invalid-name,line-too-long,missing-docstring,no-self-use,too-few-public-methods,too-many-arguments,too-many-branches,too-many-instance-attributes,too-many-locals,too-many-return-statements,too-many-statements,unused-argument,wrong-import-position src/*.py
  - sudo ./build.sh
  - sudo mv build/out/alinstaller.iso $RELEASE
  - sudo chmod 777 $RELEASE

before_deploy:
- md5sum $RELEASE

deploy:
  provider: releases
  api_key:
    secure: aqKCIPcMy2CJuPdXdLyKq3a8/+N3ayFIALyMBSIwnFGxhE3bJtzn1Nz+1AsKAaf1OOWbJpWo57j6JVEBj73+Km6OXZFh6yPeP7Si0YPvDDpO/RF/639L2qWSmI86MVMfDlfGzwgc1EcHLluVy8lhgqiy0S8yUoakG3Bza4amoCqbNkiX1ozU9171vLIJ8/ZvYQf1gCHrpn7H5LeUBOdVGOInS7EdoN9ym8LPpSSWV2meLAocw4VMd+h1Kb0j+JnsJGJ4Qfk9Hk6SvNo9B7G3ca8Au/X0QM7ZdPr3c/3NhaYtObnrWPbcfWCgFbq1BmxSvaGRuJxtm5JeMg6q9tgJPH+hN+xoY8bLyBwSkfaAWFSeWSenHeeNaQpsjudYnWKyey3yVS80jRt716J/q224Kh3FNcBRTDyeCaAPZ/02n6JzIXDYjZ19A6UdXtB4ceX/Lz27nXG+vX4neVZAKCxZqN444+pVlu85rU4MWcI9exI7/e4w+zS2O+kMLR7UClBW+GfFsX33nWEKMBx7InO9q9gEW3wU1qO9S4Yp3YY7KR9G8eu0W0Lpu2+8kdPIqv8alHFXwy9EljLr/K6HLwFQD9Ntw9PmP10KRrPozbR2UT8F9hJhDUdv2HzmFSeQ81GNimpuG0HzUsRScnoHqxJZvUI3HZzDq4G1Mpr8NRPe8io=
  file: $RELEASE
  skip_cleanup: true
  on:
    tags: true
