matrix:
  include:
  - os: linux
    sudo: required
    env:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
    - ARCH_TRAVIS_CONFIRM_YES=1
    - RELEASE="alinstaller-$(date -u +%Y.%m.%d)-$TRAVIS_TAG-x86_64.iso"
    script:
    - while true; do echo [PING]; sleep 100; done &
    - bash ./.arch-travis.sh

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - archiso
  - gtk3
  - python-babel
  - python-gobject
  - python-psutil
  - python-pylint
  - python-pythondialog
  - python-setuptools
  script:
  - sudo pacman-key --init
  - sudo pacman-key --populate archlinux
  # reduce image size:
  - sudo sed -i 's/\(mksquashfs .*\)-comp/\1-b 1024K -comp/' /bin/mkarchiso
  - ./check.sh
  - sudo ./build.sh
  - sudo mv build/out/alinstaller.iso $RELEASE
  - sudo chmod 777 $RELEASE

before_deploy:
- md5sum $RELEASE

deploy:
  provider: releases
  api_key:
    secure: 6v5PbuBePs/1Cq1ilAirbwXv0XdvA61QzXqLPYmdCHt1B772SNaZ+Gm4xaSLPCOsP0mFYpO/J3g0zbi8No7svJPW40SMdMLM+MAvMtj9VGB+yAdiCjcRvAzLRVnWcMiYpEGAnQjHnqfaq49hIOBVHid/2sf+WHBNWbW9+QYO1garPwQ1fs3dATWb5RgAXkSD0ER0OVYbQ76/2JamyymK4N44NOaLvjf2wGFsrMTmeSOGaaxJECtG/+lgmk4pC7vQFUGkD95ZtkgW0sF0V7ZeOjC1XoXdQT7aQkyiM4up96Cjz3EBuQEOnppoeGtfBnGYSjVUDjyU/9hcdphfhAnA1yf54lqfcnDovoaHuXIs1IT+1fL0dRuk8BZpF8x69pnLvN/mKwf3Rsyzi5TGYYCkI4nKNIJ4eoPnplPxuiA833hxvKO2h2cmVpaEj/z14+9hmfSYf8NGNhpYnxfT3L3ncw5G1ofL1cq0mFwAC+e8CYMWgZ2+uqiwkxkfgHbf0hcuGtyYO9TqqRh3lAS9TwDbO79v/0Ot2LQdcfCzWB9GtsJKuES9QH5mGsN8yVBgzyIH/hICqup2c38oQY8p8ThHLvaB41FAML7b6ycLq2t/85FCItD3hx4eCw6HVjms36xJQPNNjZzKCYSwCrluz3Y+y3r27fT9lDyYcdNfGg38KNg=
  file: $RELEASE
  skip_cleanup: true
  on:
    tags: true
